learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Определяет схемы URL для learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страница со списком тем
    path('topics/', views.topics, name='topics'),
    # Страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    # Редактирование темы
    path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic'),
    # Удаление темы
    path('delete_topic/<int:topic_id>', views.delete_topic, name='delete_topic'),
    # Страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Страница для редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # Удаление записи
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),
]

users/urls.py
"""Определяет схемы URL для пользователей."""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации
    path('register/', views.register, name='register'),
    # Страница пользователя
    path('<int:user_id>/profile/', views.profile, name='profile'),
    # Страница изменения пароля
    path('<int:user_id>/password/', views.change_password, name='password'),
    # Страница подтверждения удаления пользователя
    path('<int:user_id>/confirm_user_delete/', views.confirm_user_delete, name='confirm_user_delete'),
    # Удаление пользователя
    path('<int:user_id>/user_delete', views.user_delete, name='user_delete')
]

learning_logs/models.py
from django.db import models
# from django.contrib.auth.models import User
from users.models import CustomUser

# Create your models here.


class Topic(models.Model):
    """Тема, которую изучает пользователь."""
    text = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        """Возвращает строковое представление модели."""
        if len(self.text) < 30:
            string = self.text
        else:
            string = f"{self.text[:30]}..."

        return string


class Entry(models.Model):
    """Информация, изученная пользователем по теме."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое представление модели."""
        if len(self.text) < 50:
            string = self.text
        else:
            string = f"{self.text[:50]}..."

        return string

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


# Create your views here.
def index(request):
    """Домашняя страница приложения Learning Log."""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Выводит список тем."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}

    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Выводит одну тему и все её записи."""
    topic = get_object_or_404(Topic, id=topic_id)

    check_topic_owner(request, topic)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}

    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Создание новой темы."""
    if request.method != 'POST':
        # Данные не отправлялись, создаётся пустая форма.
        form = TopicForm()

    else:
        # Отправлены данные POST; обработать данные.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()

            return redirect('learning_logs:topics')

    # Вывести пустую или недействительную форму.
    context = {'form': form}

    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def edit_topic(request, topic_id):
    """Редактирование темы."""
    topic = get_object_or_404(Topic, id=topic_id)

    if request.method != 'POST':
        # Исходный запрос, форма заполняется данными текущей записи
        form = TopicForm(instance=topic)
    
    else:
        # Отправка данных POST
        form = TopicForm(instance=topic, data=request.POST)

        if form.is_valid():
            form.save()

            return redirect('learning_logs:topics')
    
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_topic.html', context)


@login_required
def delete_topic(request, topic_id):
    """Удаление темы."""
    topic = Topic.objects.get(id=topic_id)
    sum_entries = Entry.objects.filter(topic=topic).count()

    if request.method != 'POST':
        context = {'topic': topic, 'sum_entries': sum_entries}
        return render(request, 'learning_logs/delete_topic.html', context)
    
    else:
        topic.delete()
        return redirect('learning_logs:topics')


@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по теме."""
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(request, topic)

    if request.method != 'POST':
        # Данные не отправились, создаётся пустая форма.
        form = EntryForm()

    else:
        # Отправлены данные POST, обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()

            return redirect('learning_logs:topic', topic_id=topic_id)

    # Вывести пустую или недействительную форму.
    context = {'topic': topic, 'form': form}

    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(request, topic)

    if request.method != 'POST':
        # Исходный запрос, форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)

    else:
        # Отправка данных POST, обработать данные.
        form = EntryForm(instance=entry, data=request.POST)

        if form.is_valid():
            form.save()

            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    """Удаление записи."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        context = {'entry': entry, 'topic': topic}
        return render(request, 'learning_logs/delete_entry.html', context)

    else:
        entry.delete()
        return redirect('learning_logs:topic', topic_id=topic.id)


def check_topic_owner(request, topic):
    """Проверка того, что тема принадлежит указанному пользователю
    для защиты от несанкционированного доступа к записям.
    """
    if topic.owner != request.user:
        raise Http404

learning_logs/templates/learning_logs/base.html
{% load django_bootstrap5 %}

<!doctype html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,
      shrink-to-fit=no">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

<body>
  <nav class="navbar navbar-light bg-light navbar-expand-md mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
        Learning Log
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarNav" aria-controls="navbarNav"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                Topics
              </a>
            </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profile' user.id %}">Hello, {{ user.username }}.</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
              </li>
            {% endif %}
          </ul>
      </div>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>

</html>

learning_logs/templates/learning_logs/delete_entry.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h3>
    Confirmation of entry deletion.
  </h3>
{% endblock page_header %}

{% block content %}
<p>
  Are you sure you want to delete the entry?
</p>

<div class="card-body">
    {{ entry.text|linebreaks }}
</div>

<form action="{% url 'learning_logs:delete_entry' entry.id %}" method="post">
    {% csrf_token %}
    
    <button type="submit" class="btn btn-primary mb-3">delete</button>
    
    <a class="btn btn-primary mb-3"
    href="{% url 'learning_logs:topic' topic.id %}"
    role="button">back</a>
</form>



{% endblock content %}

learning_logs/templates/learning_logs/delete_topic.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h3>
    {{ topic.text }}
  </h3>
{% endblock page_header %}

{% block content %}
<p>
  Are you sure you want to delete the topic?
</p>

<p>
  It contains {{ sum_entries }} entries.
</p>

<form action="{% url 'learning_logs:delete_topic' topic.id %}" method="post">
    {% csrf_token %}
    
    <button type="submit" class="btn btn-primary mb-3">delete</button>
    
    <a class="btn btn-primary mb-3"
    href="{% url 'learning_logs:topics' %}"
    role="button">back</a>
</form>



{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h3>
    Edit entry. Topic:
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </h3>
{% endblock page_header %}

{% block content %}

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    <button type="submit" class="btn btn-primary mb-3">save changes</button>
    
    <a class="btn btn-primary mb-3"
    href="{% url 'learning_logs:topic' topic.id %}"
    role="button">back</a>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h3>
    Edit topic
  </h3>
{% endblock page_header %}

{% block content %}

<form action="{% url 'learning_logs:edit_topic' topic.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    <button type="submit" class="btn btn-primary mb-3">save changes</button>
    
    <a class="btn btn-primary mb-3"
    href="{% url 'learning_logs:topics' %}"
    role="button">back</a>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  {% if user.is_authenticated %}
    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-2">
        <h1 class="display-1">Hello, {{ user.username.capitalize }} !</h1>

        <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}"
          role="button">Topics &raquo;</a>
      </div>
    </div>

  {% else %}
    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-2">
        <h1 class="display-1">Track your learning.</h1>

        <p class="lead">Make your own Learning Log, and keep a list of the
          topics you're learning about. Whenewer you learn something new
          about a topic, make an entry summarizing what you've learned.
        </p>

        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
          role="button">Register &raquo;</a>
        
        <a class="btn btn-lg btn-primary" href="{% url 'users:login' %}"
          role="button">Login &raquo;</a>
      </div>
    </div>
  {% endif %}


{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h3>Add a new entry. Topic: 
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </h3>
{% endblock page_header %}

{% block content %}

<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    <button type="submit" class="btn btn-primary mb-3">add entry</button>
    
    <a class="btn btn-primary mb-3"
    href="{% url 'learning_logs:topic' topic.id %}"
    role="button">back</a>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h3>Add a new topic:</h3>
{% endblock page_header %}

{% block content %}

<form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    <button type="submit" class="btn btn-primary mb-3">add topic</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h3>{{ topic.text }}</h3>
{% endblock page_header %}

{% block content %}
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>

{% for entry in entries %}
<div class="card mb-3">
    <h5 class="card-header">
        {{ entry.date_added }}
        <div class="float-end">
            <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
                edit</a></small>
            <small><a href="{% url 'learning_logs:delete_entry' entry.id %}">
                delete</a></small>
        </div>
    </h5>
    <div class="card-body">
        {{ entry.text|linebreaks }}
    </div>
</div>
{% empty %}
<h5>There are no entries for this topic yet.</h5>
{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
<p>
  <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
</p>

<ul class="list-group">
    {% for topic in topics %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        <div class="float-end">
          <a href="{% url 'learning_logs:edit_topic' topic.id %}">edit</a>
          <a href="{% url 'learning_logs:delete_topic' topic.id %}">delete</a>
        </div>
      </li>
    {% empty %}
      <h5>No topics have been added yet.</h5>
    {% endfor %}
</ul>




{% endblock content %}

<!-- 
<ul>
  {% for topic in topics %}
    <li><h3>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    <h3></h3></li>
  {% empty %}
    <li><h3>No topics have been added yet.</h3></li>
  {% endfor %}
</ul> -->